backend:
  name: git-gateway
  branch: master
display_url: https://kind-varahamihira-2770af.netlify.com/products
media_folder: static/img
public_folder: /img

collections:
  - name: "burrito-reviews"
    label: "Burrito Reviews"
    folder: "src/pages/scores"
    create: true
    slug: "review--{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "burrito-review"}
      - {label: "Resteraunt Name", name: "resteraunt-name", widget: "string"}
      - {label: "Rank", name: "rank", widget: "string"}
      - {label: "Short-Description", name: "sub", widget: "text"}
      - {label: "Highlights", name: "highlights", widget: "list", default: ["Dopeness."]}
      - {label: "Rank Out of 5", name: "overall-score", widget: "number", min: 1, max: 5}
      - {label: "Flavor Score", name: "flavor-score", widget: "number", min: 1, max: 5}
      - {label: "Drippage Score", name: "drip-score", widget: "number", min: 1, max: 5}
      - {label: "Ingedients Score", name: "ingredient-score", widget: "number", min: 1, max: 5}
      - {label: "Style Score", name: "style-score", widget: "number", min: 1, max: 5}
      - {label: "Brief Review", name: 'review', widget: "text"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: "Title", name: "title", widget: "string", default: "Home"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "List Name", name: 'list-name', widget: "string"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string", default: "About"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "List Name", name: 'list-name', widget: "string"}
