backend:
  name: git-gateway
  branch: staging
display_url: https://burrito-six.netlify.com
media_folder: static/img
public_folder: /img

collections:
  - name: "burrito-reviews"
    label: "Burrito Reviews"
    folder: "src/pages/scores"
    create: true
    slug: "review--{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "burrito-review"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", format: "MMM Do YY"}
      - {label: "Restaurant Name", name: "restaurant_name", widget: "string"}
      - {label: "Rank", name: "rank", widget: "number", valueType: "float"}
      - {label: "Short-Description", name: "sub", widget: "text"}
      - label: "Highlights"
        name: "highlights"
        widget: "list"
        allow_add: true
        fields:
          - {label: highlight, name: highlight_data, widget: string}
      - {label: "Rank Out of 5", name: "overall_score", widget: "number", valueType: "float", min: 1, max: 5}
      - {label: "Flavor Score", name: "flavor_score", widget: "number", valueType: "float", min: 1, max: 5}
      - {label: "Drippage Score", name: "drip_score", widget: "number", valueType: "float", min: 1, max: 5}
      - {label: "Ingredients Score", name: "ingredient_score", widget: "number", valueType: "float", min: 1, max: 5}
      - {label: "Style Score", name: "style_score", widget: "number", valueType: "float", min: 1, max: 5}
      - {label: "Brief Review", name: 'review', widget: "text"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: "Is A Page", name: "isPage", widget: "hidden", default: true}
          - {label: "Title", name: "title", widget: "string", default: "Home"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "List Name", name: "list_name", widget: "string"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Is A Page", name: "isPage", widget: "hidden", default: true}
          - {label: "Title", name: "title", widget: "string", default: "About"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "List Name", name: "list_name", widget: "string"}
          - {label: "Blog post content", name: "body", widget: "markdown"}
